name: mols2grid
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - jinja2>=2.11.0
  - ipywidgets>=7,<9
  - pytest==6.2.5
  - selenium==3.141.0
  - codecov==2.1.12
  - jupyterlab
  - jupyter-packaging==0.12.0
  - nodejs==17.9.0
  - yarn==1.22.18
