name: mols2grid
channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets=8
  - notebook=7
  - mistune<3.0.0
  - nbsphinx==0.8.8
  - nodejs==18.12.1
  - pandas=2.1
  - pip
  - rdkit
  - recommonmark==0.7.1
  - sphinx==4.5.0
  - yarn==1.22.19
  - pip:
    - py3dmol==1.7.0
    - sphinx-rtd-theme==1.0.0
    - sphinx-mdinclude==0.5.2
