name: build
on:
  release:
    types: [released]
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

env:
  IS_PRERELEASE: ${{ github.event_name == 'workflow_dispatch' }}

jobs:
  build:
    name: Build package
    uses: ./.github/workflows/_build-package.yml
    with:
      check-prerelease: ${{ env.IS_PRERELEASE }}  

  publish:
    name: Publish to PyPI and NPM
    runs-on: ubuntu-latest

    steps:
    - name: Retrieve cached package
      uses: actions/cache/restore@v3
      id: cache-mols2grid
      with:
        path: |
          dist/mols2grid-*.whl
          dist/mols2grid-*.tar.gz
        key: mols2grid-${{ runner.os }}-${{ github.sha }}

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}

    - name: Publish the package through NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        PRE_RELEASE: ${{ env.IS_PRERELEASE }}